# -*- coding: utf-8 -*-
"""Animal_Comparison_CNN_Model .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzwNWV0w8m8Qv_C_NRC4BH96nA-94WWj
"""

!pip install tensorflow tensorflow-datasets

#Loading the images
import tensorflow_datasets as tfds

dataset, info = tfds.load("cycle_gan/horse2zebra", with_info=True, as_supervised=True)
bike_ds = dataset["trainB"]   # This contains zebra images in the horse2zebra dataset

print("Total zebra images:", info.splits["trainB"].num_examples)

import tensorflow as tf

# Step 1 — Preprocessing and labeling, combine into one dataset
IMG_SIZE = 128
BATCH = 32
AUTOTUNE = tf.data.AUTOTUNE

def preprocess_image(image):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = tf.cast(image, tf.float32) / 255.0
    return image

def map_horse(image, _):
    return preprocess_image(image), 0   # label 0 -> horse

def map_zebra(image, _):
    return preprocess_image(image), 1   # label 1 -> zebra

horses_labeled = dataset['trainA'].map(map_horse, num_parallel_calls=AUTOTUNE)
zebras_labeled = dataset['trainB'].map(map_zebra, num_parallel_calls=AUTOTUNE)

# Combine datasets
combined = horses_labeled.concatenate(zebras_labeled)
combined = combined.shuffle(2000, seed=42)

# Step 2 — Training/validation split using dataset.take / skip
total = 0
for _ in combined:
    total += 1
print("Total combined examples (approx):", total)

# Note: TFDS splits often have ~1000 images per domain; adjust if needed.
val_frac = 0.2
val_size = int(total * val_frac)

val_ds = combined.take(val_size).batch(BATCH).prefetch(AUTOTUNE)
train_ds = combined.skip(val_size).batch(BATCH).prefetch(AUTOTUNE)

print("Train batches:", tf.data.experimental.cardinality(train_ds).numpy(),
      "Val batches:", tf.data.experimental.cardinality(val_ds).numpy())

# Step 3 — Building a small CNN classifier
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3)),
    layers.Conv2D(32, 3, activation="relu"),
    layers.MaxPool2D(),
    layers.Conv2D(64, 3, activation="relu"),
    layers.MaxPool2D(),
    layers.Conv2D(128, 3, activation="relu"),
    layers.MaxPool2D(),
    layers.Flatten(),
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.4),
    layers.Dense(1, activation="sigmoid")   # binary output
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# Step 4— Training the model
EPOCHS = 12

history = model.fit(
    train_ds,
    epochs=EPOCHS,
    validation_data=val_ds
)

# Step 5 — Plotting
import matplotlib.pyplot as plt

plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='train acc')
plt.plot(history.history['val_accuracy'], label='val acc')
plt.title('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.title('Loss')
plt.legend()
plt.show()

#Step 6 Visualizing
import numpy as np
import matplotlib.pyplot as plt

# get one batch from validation
for images, labels in val_ds.take(1):
    preds = model.predict(images)
    preds = (preds.flatten() > 0.5).astype(int)
    images = images.numpy()
    labels = labels.numpy()
    break

# show 6 examples
plt.figure(figsize=(12,6))
for i in range(6):
    ax = plt.subplot(2,3,i+1)
    plt.imshow(images[i])
    plt.title(f"true: {labels[i]}  pred: {preds[i]}")
    plt.axis('off')
plt.show()

#Data augmentation
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    layers.RandomContrast(0.2),
])

#Modifying training
def augment(image, label):
    image = data_augmentation(image)
    return image, label

train_ds_aug = train_ds.map(lambda x, y: augment(x, y),
                            num_parallel_calls=AUTOTUNE)
train_ds_aug = train_ds_aug.prefetch(AUTOTUNE)

#Training
history = model.fit(
    train_ds_aug,
    epochs=EPOCHS,
    validation_data=val_ds
)

!pip install tensorflow tensorflow-datasets

import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

#Loading the dataset
dataset, info = tfds.load("cycle_gan/horse2zebra", with_info=True, as_supervised=True)

trainA = dataset["trainA"]   # horses
trainB = dataset["trainB"]   # zebras

print("Horse images:", info.splits["trainA"].num_examples)
print("Zebra images:", info.splits["trainB"].num_examples)

#Preprocessing
IMG_SIZE = 128
BATCH = 32
AUTOTUNE = tf.data.AUTOTUNE

def preprocess(img):
    img = tf.image.resize(img, (IMG_SIZE, IMG_SIZE))
    return tf.cast(img, tf.float32) / 255.0

def map_horse(img, _):
    return preprocess(img), 0

def map_zebra(img, _):
    return preprocess(img), 1

horses = trainA.map(map_horse, num_parallel_calls=AUTOTUNE)
zebras  = trainB.map(map_zebra, num_parallel_calls=AUTOTUNE)

# combine data
combined = horses.concatenate(zebras).shuffle(2000, seed=42)

#Splitting the training and validation data
total = 0
for _ in combined:
    total += 1

val_size = int(total * 0.2)

val_ds   = combined.take(val_size).batch(BATCH).prefetch(AUTOTUNE)
train_ds = combined.skip(val_size).batch(BATCH)

#Data Augmentation
data_aug = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    layers.RandomContrast(0.2),
])

def augment(img, label):
    return data_aug(img), label

train_ds = train_ds.map(augment, num_parallel_calls=AUTOTUNE)
train_ds = train_ds.prefetch(AUTOTUNE)

#CNN Model
model = models.Sequential([
    layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3)),

    layers.Conv2D(32, 3, activation="relu"),
    layers.BatchNormalization(),
    layers.MaxPool2D(),

    layers.Conv2D(64, 3, activation="relu"),
    layers.BatchNormalization(),
    layers.MaxPool2D(),

    layers.Conv2D(128, 3, activation="relu"),
    layers.BatchNormalization(),
    layers.MaxPool2D(),

    layers.Conv2D(256, 3, activation="relu"),
    layers.BatchNormalization(),
    layers.MaxPool2D(),

    layers.Flatten(),
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

#LR Scheduler
lr_scheduler = tf.keras.callbacks.ReduceLROnPlateau(
    monitor="val_loss",
    patience=2,
    factor=0.5,
    min_lr=1e-6
)

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=4,
    restore_best_weights=True
)

#Training the model
history = model.fit(
    train_ds,
    epochs=20,
    validation_data=val_ds,
    callbacks=[lr_scheduler, early_stop]
)

#Visualization
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label="train acc")
plt.plot(history.history['val_accuracy'], label="val acc")
plt.legend()
plt.title("Accuracy")

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label="train loss")
plt.plot(history.history['val_loss'], label="val loss")
plt.legend()
plt.title("Loss")

plt.show()

#Prediction
for images, labels in val_ds.take(1):
    preds = model.predict(images)
    preds = (preds.flatten() > 0.5).astype(int)
    break

plt.figure(figsize=(12,6))
for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(images[i])
    plt.title(f"True: {labels[i].numpy()}  Pred: {preds[i]}")
    plt.axis("off")

plt.show()

#Final Classification report
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Collect all true labels & predictions from validation set
y_true = []
y_pred = []

for images, labels in val_ds:
    preds = model.predict(images)
    preds = (preds.flatten() > 0.5).astype(int)

    y_true.extend(labels.numpy())
    y_pred.extend(preds)

y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Print Classification Report
print("Classification Report:")
print(classification_report(y_true, y_pred, target_names=["Horse", "Zebra"]))

# Print Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# Compute confusion matrix
cm = confusion_matrix(y_true, y_pred)
labels = ["Horse", "Zebra"]

# Plot heatmap
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels)

plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix Heatmap")
plt.show()